      - name: Install Dependencies
        run: |
          pip install -r MLProject/requirements.txt

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        # Kita jalankan langsung scriptnya karena library sudah terinstall di local runner
        run: python MLProject/modelling.py